### ISSUE TITLE
Keep Rustup in the installation directory

### ISSUE THREAD

**Issue by whitfin** [code-lever/asdf-rust#3] opened 2017-01-12 20:40 UTC
I'm pretty new to the Rust setup, but it appears that Rustup is pretty important for cross compilation: https://github.com/rust-lang-nursery/rustup.rs

It appears that this plugin downloads it to a temp directory and throws it away... have you considered keeping it around in the bin dir? This would assist in installing new toolchains.

**Comment by nickveys** [comment] 2017-02-04 00:07
The asdf scripts don't seem to be in the business of trying to do more than just install and manage the installed versions of the languages.  I'm not sure what putting the rustup file somewhere would help with?  Is there an testable problem caused by not keeping it around?

**Comment by whitfin** [comment] 2017-02-04 00:34
@nickveys sure, you use `rustup` to cross-compile. Not being able to is a problem :p

**Comment by nickveys** [comment] 2017-03-30 01:55
Just merged #10 to add this.

**Closed as completed by nickveys** 2017-03-30 01:55 UTC
